from app import db

class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(200))
    middle_name = db.Column(db.String(200))
    last_name = db.Column(db.String(200))
    email = db.Column(db.String(200))
    joined_e_date = db.Column(db.Date)
    joined_n_date = db.Column(db.Date)
    dob_e = db.Column(db.Date)
    dob_n = db.Column(db.Date)
    citizenship_no = db.Column(db.String(200))
    gender = db.Column(db.String(200))
    p_country = db.Column(db.String(200))
    p_zone = db.Column(db.String(200))
    p_district = db.Column(db.String(200))
    p_address = db.Column(db.String(200))
    p_street = db.Column(db.String(200))
    t_country = db.Column(db.String(200))
    t_zone = db.Column(db.String(200))
    t_address = db.Column(db.String(200))
    t_street = db.Column(db.String(200))
    t_district = db.Column(db.String(200))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User')
    department_id = db.Column(db.Integer, db.ForeignKey('department.id'), nullable=False)
    department = db.relationship('Department')
    branch_id = db.Column(db.Integer, db.ForeignKey('branch.id'), nullable=False)
    branch = db.relationship('Branch')
    mode_id = db.Column(db.Integer, db.ForeignKey('mode.id'), nullable=False)
    mode = db.relationship('Mode')
    sub_department_id = db.Column(db.Integer, db.ForeignKey('sub_department.id'), nullable=False)
    sub_department = db.relationship('SubDepartment')
    designation_id = db.Column(db.Integer, db.ForeignKey('designation.id'), nullable=False)
    designation = db.relationship('Designation')
    grade_id = db.Column(db.Integer, db.ForeignKey('grade.id'), nullable=False)
    grade = db.relationship('Grade')
    status_id = db.Column(db.Integer, db.ForeignKey('status.id'), nullable=False)
    status = db.relationship('Status')
    type_id = db.Column(db.Integer, db.ForeignKey('type.id'), nullable=False)
    type = db.relationship('Type')
    mobile_number = db.Column(db.BigInteger)
